version: '3'

services:
  web-service:
    image: nginx:latest
    container_name: web-service
    ports:
     - 8081:80
    volumes:
      - www:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
     - teko-net
  php-service:
    image: nanoninja/php-fpm
    container_name: php-service
    volumes:
     - www:/var/www/html
    networks:
     - teko-net
  mysql-service:
    image: mysql:latest
    container_name: mysql-service
    volumes:
     - database:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=rootpw
    networks:
     - teko-net
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: 'C:\Temp\root\www'
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: 'C:\Temp\root\database'
      o: bind
networks:
  teko-net:
    # Mit der Option 'external' wird ein bereits vorhandenes netzwerk ausgewählt
    external:
      name: teko-net